### ISSUE TITLE
[FEATURE] VinDrBodyPartXR Classification Model

### ISSUE THREAD

**Issue by jasonadriann** [KalbeDigitalLab/AI-Vision-Lightning-Pipeline#16]
## 🚨🚨 Feature Request

- [x] A new implementation (Improvement, Extension)

### Is your feature request related to a problem?

A new model for body part x-ray classification using ResNet-18.

### Description of the possible solution

Model is developed using [PyTorch Lightning Module](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html) and the training is config using [Hydra](https://hydra.cc/). Testing also included using pytest.

**Comment by haritsahm** [comment]
close as of #15 #17
