### ISSUE TITLE
[FEATURE] Improvement Model to Breast Cancer Classification

### ISSUE THREAD

**Issue by IstiqomahUswatunH** [KalbeDigitalLab/AI-Vision-Lightning-Pipeline#9]
## 🚨🚨 Feature Request

- [ ] A new implementation (Improvement, Extension)

### Is your feature request related to a problem?

Improving breast cancer classification model by implementing the ResNet architecture. ResNet is renowned for its exceptional performance in image classification tasks, and I believe this enhancement can significantly boost the accuracy and effectiveness of breast cancer diagnosis.

### Description of the possible solution

source dataset: https://www.kaggle.com/code/shangguang/breast-cancer-segmenter-mask-r-cnn/input
Reference: http://www.annalsofrscb.ro/index.php/journal/article/view/6604/4980

**Comment by haritsahm** [comment]
close as of #12 #18
